import { describe, it, expect } from 'vitest';
import {
  scoreEmergingFromText,
  detectEmergingTech,
  generateRoadmapsFromEmerging,
} from '../trendAnalyzer';
import type { TechUpdate } from '../types';

describe('trendAnalyzer', () => {
  it('scoreEmergingFromText 识别 Agent 相关信号', () => {
    const scores = scoreEmergingFromText('New agentic AI workflow with MCP integration');
    expect(scores.some((s) => s.label.includes('Agentic') || s.label.includes('MCP'))).toBe(true);
  });

  it('detectEmergingTech 过滤已存在的技术方向', () => {
    const updates: TechUpdate[] = [{
      id: 't1',
      sourceId: 'hn-ai',
      title: 'WebGPU for edge AI rendering',
      summary: 'agentic workflow with WebGPU acceleration',
      url: 'https://example.com',
      publishedAt: new Date().toISOString(),
      roadmapKeys: ['ai-agent'],
      tags: [],
      keywords: ['WebGPU', 'agentic'],
    }];
    const existing = [{ key: 'ai-agent', title: 'AI Agent' } as never];
    const emerging = detectEmergingTech(updates, existing, 1);
    expect(emerging.every((e) => e.key !== 'ai-agent')).toBe(true);
    expect(emerging.length).toBeGreaterThan(0);
  });

  it('generateRoadmapsFromEmerging 生成四阶段学习框架', () => {
    const emerging = [{
      name: 'WebGPU',
      key: 'webgpu',
      score: 4,
      signals: ['hn-ai'],
      suggestedColor: '#3B82F6',
      suggestedDesc: '新兴图形计算技术',
    }];
    const roadmaps = generateRoadmapsFromEmerging(emerging);
    expect(roadmaps).toHaveLength(1);
    expect(roadmaps[0].stages).toHaveLength(4);
    expect(roadmaps[0].autoGenerated).toBe(true);
  });
});
