'use client';

import React, { useState } from 'react';
import { NodeIndexOutlined, CheckOutlined } from '@ant-design/icons';
import { LEVEL_COLORS, type RoadmapLevel } from '../../data/learningRoadmaps';
import { useMergedRoadmaps } from '../../hooks/useMergedRoadmaps';
import './index.less';

const LEVELS: RoadmapLevel[] = ['入门', '进阶', '高级', '实战'];
type CategoryTab = 'all' | 'language' | 'tech-direction';

const CATEGORY_LABELS: Record<CategoryTab, string> = {
  all: '全部',
  language: '编程语言',
  'tech-direction': '技术方向',
};

const Roadmap: React.FC = () => {
  const { roadmaps, languageRoadmaps, techRoadmaps } = useMergedRoadmaps();
  const [category, setCategory] = useState<CategoryTab>('all');

  const filtered =
    category === 'all'
      ? roadmaps
      : category === 'language'
        ? languageRoadmaps
        : techRoadmaps;

  const [activeKey, setActiveKey] = useState(filtered[0]?.key ?? roadmaps[0]?.key);
  const active = filtered.find((r) => r.key === activeKey) ?? filtered[0] ?? roadmaps[0];
  const totalTopics = active.stages.reduce((sum, s) => sum + s.topics.length, 0);

  const handleCategoryChange = (cat: CategoryTab) => {
    setCategory(cat);
    const list = cat === 'all' ? roadmaps : cat === 'language' ? languageRoadmaps : techRoadmaps;
    if (list.length > 0) setActiveKey(list[0].key);
  };

  return (
    <div className="roadmap-page">
      <section className="rm-hero">
        <div className="rm-hero-glow" />
        <div className="rm-hero-inner">
          <span className="rm-hero-badge"><NodeIndexOutlined /> 学习路线</span>
          <h1 className="rm-hero-title">编程语言 & 技术方向学习路线</h1>
          <p className="rm-hero-sub">
            涵盖编程语言与 11 大技术方向专属路径，由「入门 → 进阶 → 高级 → 实战」四阶段组成，清晰列出每个阶段需要掌握的知识点
          </p>
          <div className="rm-legend">
            {LEVELS.map((lv) => (
              <span key={lv} className="rm-legend-item">
                <i style={{ background: LEVEL_COLORS[lv] }} />{lv}
              </span>
            ))}
          </div>
        </div>
      </section>

      <div className="rm-category-bar">
        {(Object.keys(CATEGORY_LABELS) as CategoryTab[]).map((cat) => (
          <button
            key={cat}
            type="button"
            className={`rm-category-btn ${category === cat ? 'active' : ''}`}
            onClick={() => handleCategoryChange(cat)}
          >
            {CATEGORY_LABELS[cat]}
            <span className="rm-category-count">
              {cat === 'all' ? roadmaps.length : cat === 'language' ? languageRoadmaps.length : techRoadmaps.length}
            </span>
          </button>
        ))}
      </div>

      <div className="rm-tabs">
        {filtered.map((r) => (
          <button
            key={r.key}
            type="button"
            className={`rm-tab ${activeKey === r.key ? 'active' : ''}`}
            style={activeKey === r.key ? { background: r.color, borderColor: r.color } : { color: r.color }}
            onClick={() => setActiveKey(r.key)}
          >
            <span className="rm-tab-icon">{r.icon}</span>
            {r.title}
            {r.autoGenerated && <span className="rm-auto-tag">AI</span>}
          </button>
        ))}
      </div>

      <div className="rm-content">
        <div className="rm-overview" style={{ borderColor: `${active.color}33` }}>
          <div className="rm-overview-icon" style={{ color: active.color, background: `${active.color}14` }}>
            {active.icon}
          </div>
          <div className="rm-overview-text">
            <h2 className="rm-overview-title">{active.title} 学习路线</h2>
            <p className="rm-overview-desc">{active.desc}</p>
            {active.lastUpdated && (
              <span className="rm-updated">最近更新：{new Date(active.lastUpdated).toLocaleDateString('zh-CN')}</span>
            )}
          </div>
          <div className="rm-overview-stats">
            <div className="rm-ov-stat"><b>{active.stages.length}</b><i>阶段</i></div>
            <div className="rm-ov-stat"><b>{totalTopics}</b><i>知识点</i></div>
          </div>
        </div>

        <div className="rm-timeline">
          {active.stages.map((stage, idx) => {
            const lvColor = LEVEL_COLORS[stage.level];
            return (
              <div key={`${stage.level}-${stage.name}`} className="rm-stage">
                <div className="rm-stage-rail">
                  <span className="rm-stage-node" style={{ background: lvColor }}>{idx + 1}</span>
                  {idx < active.stages.length - 1 && <span className="rm-stage-line" />}
                </div>
                <div className="rm-stage-card">
                  <div className="rm-stage-head">
                    <span className="rm-stage-level" style={{ color: lvColor, background: `${lvColor}1a` }}>{stage.level}</span>
                    <h3 className="rm-stage-name">{stage.name}</h3>
                    <span className="rm-stage-count">{stage.topics.length} 项</span>
                  </div>
                  <div className="rm-topics">
                    {stage.topics.map((t) => (
                      <span key={t} className="rm-topic" style={{ ['--dot' as string]: lvColor } as React.CSSProperties}>
                        <CheckOutlined className="rm-topic-check" style={{ color: lvColor }} />
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default Roadmap;
