import React from 'react';
import { ExperimentOutlined } from '@ant-design/icons';
import type { Roadmap } from '../../data/learningRoadmaps';
import type { EmergingTech } from './types';

/** 为新兴技术自动生成基础学习框架 */
export function generateRoadmapTemplate(tech: EmergingTech): Roadmap {
  const base = tech.name;
  return {
    key: tech.key,
    title: base,
    category: 'tech-direction',
    color: tech.suggestedColor,
    icon: React.createElement(ExperimentOutlined),
    desc: tech.suggestedDesc,
    autoGenerated: true,
    lastUpdated: new Date().toISOString(),
    stages: [
      {
        level: '入门',
        name: '基础认知',
        topics: [
          `${base} 核心概念`,
          `${base} 生态与工具链`,
          `开发环境搭建`,
          `Hello World 实践`,
          `官方文档导读`,
        ],
      },
      {
        level: '进阶',
        name: '核心能力',
        topics: [
          `${base} 常用 API / SDK`,
          `最佳实践与设计模式`,
          `与现有技术栈集成`,
          `调试与问题排查`,
          `社区资源与案例`,
        ],
      },
      {
        level: '高级',
        name: '深入原理',
        topics: [
          `${base} 架构原理`,
          `性能优化策略`,
          `安全与合规考量`,
          `规模化部署`,
          `前沿特性跟踪`,
        ],
      },
      {
        level: '实战',
        name: '项目落地',
        topics: [
          `完整项目实战`,
          `生产环境部署`,
          `监控与运维`,
          `团队协作规范`,
          `持续学习与迭代`,
        ],
      },
    ],
  };
}
